services:
  test-db:
    image: postgres:18.1
    container_name: test-db
    environment:
      - POSTGRES_PASSWORD=change-me
      - POSTGRES_USER=sa
      - POSTGRES_DB=postgres
    tmpfs: /var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - test-nw

  test-py:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/test-py:3.14.2
    container_name: test-py
    tty: true
    networks:
      - test-nw

networks:
  test-nw: