services:
  test-db:
    image: postgres:18.1
    container_name: test-db
    environment:
      - POSTGRES_PASSWORD=change-me
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample_db
    tmpfs: /var/lib/postgresql
    ports:
      - 5432:5432